In [6]:
import numpy as np
a=np.arange(15).reshape(3,5)#it will create array of sequence
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [7]:
a.shape#

(3, 5)

In [8]:
a.ndim#####dimension

2

In [9]:
a.dtype

dtype('int32')

In [10]:
a.itemsize####no. of bytes for each item in array

4

In [11]:
a.size #####no. of elements in an array

15

In [12]:
b=np.array([1,2,3])
b

array([1, 2, 3])

In [16]:
c = np.array([(1,2,3),(4,5,6)])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
c = np.array([(1.6,2.3,3),(4,5,6)],dtype=float)
c

array([[ 1.6,  2.3,  3. ],
       [ 4. ,  5. ,  6. ]])

In [22]:
complx=np.array([(1,2),(3,4)],dtype=complex)
complx

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

In [23]:
complx.real ####display real value

array([[ 1.,  2.],
       [ 3.,  4.]])

In [24]:
complx.imag  ######display imaginary value

array([[ 0.,  0.],
       [ 0.,  0.]])

In [25]:
np.zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [26]:
np.ones((3,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [30]:
np.eye(3,dtype=int) 

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [29]:
np.empty((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [33]:
np.arange(1,17,3).reshape(2,3) ##number sequence with interval 3

array([[ 1,  4,  7],
       [10, 13, 16]])

In [37]:
np.linspace(1,2,9).reshape(3,3) #######will generate 9 numbers based on range

array([[ 1.   ,  1.125,  1.25 ],
       [ 1.375,  1.5  ,  1.625],
       [ 1.75 ,  1.875,  2.   ]])

In [44]:
from numpy import *
x=np.linspace(0,2*pi,50)
f=np.sin(x)
f.reshape(5,10)

array([[  0.00000000e+00,   1.27877162e-01,   2.53654584e-01,
          3.75267005e-01,   4.90717552e-01,   5.98110530e-01,
          6.95682551e-01,   7.81831482e-01,   8.55142763e-01,
          9.14412623e-01],
       [  9.58667853e-01,   9.87181783e-01,   9.99486216e-01,
          9.95379113e-01,   9.74927912e-01,   9.38468422e-01,
          8.86599306e-01,   8.20172255e-01,   7.40277997e-01,
          6.48228395e-01],
       [  5.45534901e-01,   4.33883739e-01,   3.15108218e-01,
          1.91158629e-01,   6.40702200e-02,  -6.40702200e-02,
         -1.91158629e-01,  -3.15108218e-01,  -4.33883739e-01,
         -5.45534901e-01],
       [ -6.48228395e-01,  -7.40277997e-01,  -8.20172255e-01,
         -8.86599306e-01,  -9.38468422e-01,  -9.74927912e-01,
         -9.95379113e-01,  -9.99486216e-01,  -9.87181783e-01,
         -9.58667853e-01],
       [ -9.14412623e-01,  -8.55142763e-01,  -7.81831482e-01,
         -6.95682551e-01,  -5.98110530e-01,  -4.90717552e-01,
         -3.75267005e-01

In [46]:
a=np.arange(4)
a
b=np.array([10,20,30,40])
b

array([10, 20, 30, 40])

In [47]:
a+b

array([10, 21, 32, 43])

In [48]:
a-b

array([-10, -19, -28, -37])

In [49]:
b*2

array([20, 40, 60, 80])

In [51]:
mod(b,3)

array([1, 2, 0, 1], dtype=int32)

In [53]:
A = np.array( [[1,1],[0,1]]) 
A

array([[1, 1],
       [0, 1]])

In [54]:
B = np.array( [[2,4],[4,5]])
B

array([[2, 4],
       [4, 5]])

In [55]:
A*B  ###ELEMENTWISE PRODUCT

array([[2, 4],
       [0, 5]])

In [56]:
A.dot(B)

array([[6, 9],
       [4, 5]])

In [57]:
np.dot(A,B)

array([[6, 9],
       [4, 5]])

In [60]:
B > 4

array([[False, False],
       [False,  True]], dtype=bool)

In [63]:
a=np.ones((2,3),dtype=int)        
          
a

array([[1, 1, 1],
       [1, 1, 1]])

In [64]:
b=np.random.random((2,3))
b

array([[ 0.71367179,  0.83824601,  0.5471025 ],
       [ 0.68970989,  0.10726124,  0.77268716]])

In [67]:
b+=a
b

array([[ 2.71367179,  2.83824601,  2.5471025 ],
       [ 2.68970989,  2.10726124,  2.77268716]])

In [68]:
a*=3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [69]:
b=np.arange(12).reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [70]:
b.sum(axis=0) # sum of each column

array([18, 22, 26])

In [71]:
b.min(axis=1) # min of each row

array([0, 3, 6, 9])

In [72]:
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [73]:
b.cumsum(axis=1) # cumulative sum along each row

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21],
       [ 9, 19, 30]], dtype=int32)