In [1]:
import numpy as np

In [7]:
a = np.array([[1,2,3],[4,5,6]],dtype=int)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
a.flags
#C_CONTIGUOUS : True if its row measure
#F_CONTIGUOUS : False for column

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [13]:
a=np.array([[1,2,3],[4,5,6]],dtype=np.int64,order='F')
#####
#F_CONTIGUOUS TO TRUE SIMILARLY'C' FORC_CONTIGUOUS

In [12]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [15]:
a.shape

(2, 3)

In [16]:
a.strides ##it will provide the size in each dimension row and column

(8, 16)

In [17]:
a.ndim##number of dimension

2

In [18]:
a.size##no of elements

6

In [19]:
a.itemsize####each element space in byte

8

In [20]:
a.nbytes###total space used in bytes

48

In [21]:
b=a.T######transpose
b

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int64)

In [22]:

a.real######it will print real part

array([[1, 2, 3],
       [4, 5, 6]], dtype=int64)

In [23]:
a.imag######imaginary part

array([[0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [30]:
from numpy import *
a=array([[1,5,3],[10,1,2],[10,30,20]],dtype=int64,copy=False,order='C',ndmin=2,subok=False)
a

array([[ 1,  5,  3],
       [10,  1,  2],
       [10, 30, 20]], dtype=int64)

In [31]:
arg_max_row=argmax(a,axis=0)######it will display max indices row-wise
arg_max_row

array([1, 2, 2], dtype=int64)

In [32]:
arg_max_col=argmax(a,axis=1)###it will display max indices column -wise
arg_max_col

array([1, 0, 1], dtype=int64)

In [34]:
arg_min_row=argmin(a,axis=0)
arg_min_col=argmax(a,axis=1)###give min indices
arg_min_col

array([1, 0, 1], dtype=int64)

In [35]:
####kind of sort----quicksort,mergesort,heapsort

In [40]:
a

array([[ 1,  5,  3],
       [10,  1,  2],
       [10, 30, 20]], dtype=int64)

In [38]:
sort_row_quick=argsort(a,axis=0,kind='quicksort')
sort_row_quick


array([[0, 1, 1],
       [1, 0, 0],
       [2, 2, 2]], dtype=int64)

In [41]:
sort_row_heap=argsort(a,axis=0,kind='heapsort')
sort_row_heap

array([[0, 1, 1],
       [2, 0, 0],
       [1, 2, 2]], dtype=int64)

In [43]:
sort_col_quick=argsort(a,axis=1,kind='quicksort')
sort_col_quick

array([[0, 2, 1],
       [1, 2, 0],
       [0, 2, 1]], dtype=int64)

In [44]:
sort_col_heap=argsort(a,axis=1,kind='heapsort')
sort_col_heap

array([[0, 2, 1],
       [1, 2, 0],
       [0, 2, 1]], dtype=int64)

In [47]:
a

array([[ 1,  5,  3],
       [10,  1,  2],
       [10, 30, 20]], dtype=int64)

In [46]:
#####choose -Extract element from multidimensional array

In [54]:
chose_raise=choose([0,2,1],a,mode='raise')
#0[0]-o throw zero first element--1
#2[1]-1st position from 2nd row
#1[2]-2nd position form 1 row 
#Note-position starts with value 0
chose_raise

array([ 1, 30,  2], dtype=int64)

In [51]:
chose_clip=choose([0,2,1],a,mode='clip') 
chose_clip


array([ 1, 30,  2], dtype=int64)

In [57]:
chose_clip=choose([0,4,1],a,mode='clip') 
#if indices increase the max length then it will take max value
#in our scenario max index for array is 2
chose_clip

array([ 1, 30,  2], dtype=int64)

In [60]:
chose_wrap=choose([0,4,1],a,mode='wrap')
chose_wrap
#4--it will work as cycle--0,1,2--so 4 will be 0

array([1, 1, 2], dtype=int64)

In [61]:
a

array([[ 1,  5,  3],
       [10,  1,  2],
       [10, 30, 20]], dtype=int64)

In [62]:
clip_a=clip(a,2,10)
#syntax-clip(a,min a,max a)
#element greater lessthan 2 converted to 2,greater than 10 converted to 10
clip_a

array([[ 2,  5,  3],
       [10,  2,  2],
       [10, 10, 10]], dtype=int64)

In [63]:
cmrs_row=compress([0,1,1],a,axis=0)
###it will pass boolean value in argument and result will be shown
cmrs_row

array([[10,  1,  2],
       [10, 30, 20]], dtype=int64)

In [69]:
cmrs_col=compress([1,1,0],a,axis=1)
cmrs_col

array([[ 1,  5],
       [10,  1],
       [10, 30]], dtype=int64)

In [70]:
y=a.copy()
y

array([[ 1,  5,  3],
       [10,  1,  2],
       [10, 30, 20]], dtype=int64)

In [72]:
y.fill(111)
y

array([[111, 111, 111],
       [111, 111, 111],
       [111, 111, 111]], dtype=int64)

In [74]:
cp=cumprod(a,dtype=int,axis=0)
cp

array([[  1,   5,   3],
       [ 10,   5,   6],
       [100, 150, 120]], dtype=int32)

In [82]:
cp=cumprod(a,dtype=int,axis=1)
cp

array([[   1,    5,   15],
       [  10,   10,   20],
       [  10,  300, 6000]], dtype=int32)

In [84]:
cp=cumprod(a,dtype=int,axis=None)
cp

array([      1,       5,      15,     150,     150,     300,    3000,
         90000, 1800000], dtype=int32)

In [88]:
cp1=ndarray((9),dtype=int)
cp_arr=cumprod(a,dtype=int,axis=None,out=cp1)
cp_arr

array([      1,       5,      15,     150,     150,     300,    3000,
         90000, 1800000])

In [90]:
cs1=ndarray(a,dtype=int)
cs_axis0=cumsum(a,dtype=int,axis=None,out=cs1)
cs_axis0

TypeError: only length-1 arrays can be converted to Python scalars