In [1]:
import numpy as np

a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]


In [2]:
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

(2, 3)
1 2 4


In [ ]:
#Numpy also provides many functions to create arrays:


In [4]:
import numpy as np

a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,3), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

[[ 0.  0.]
 [ 0.  0.]]
[[ 1.  1.]]
[[ 7.  7.  7.]
 [ 7.  7.  7.]]
[[ 1.  0.]
 [ 0.  1.]]
[[ 0.90793074  0.49869212]
 [ 0.93607068  0.47665684]]


C:\Program Files\Anaconda3\lib\site-packages\numpy\core\numeric.py:301: FutureWarning: in the future, full((2, 3), 7) will return an array of dtype('int32')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)


In [ ]:
'''Array indexing
Numpy offers several ways to index into arrays.

Slicing: Similar to Python lists, numpy arrays can be sliced. 
Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

'''

In [17]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [18]:
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]

b=a[:2,1:3]
print(b)

[[2 3]
 [6 7]]


In [19]:
# A slice of an array is a view into the same data, so modifying it
# will modify the original array.

print(a[0, 1])
b[0,0]=77 # b[0, 0] is the same piece of data as a[0, 1]
print(a[0,1]) # Prints "77"



2
77


In [21]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:

row_1=a[1,:]
row_2=a[1:2,:]
print(row_1, row_1.shape)
print(row_2, row_2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


In [22]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [25]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])
print(a)

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

[[1 2]
 [3 4]
 [5 6]]
[1 4 5]


In [24]:
# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

[1 4 5]


In [27]:
# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"
# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

[2 2]
[2 2]


In [28]:
print(a[[0,0],[1,0]])

[2 1]


In [29]:
import numpy as np

# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [30]:
b=np.array([0,2,0,1])
print(b)

[0 2 0 1]


In [43]:
print(a[np.arange(4)],b)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] [0 2 0 1]


In [36]:
print(a[np.arange(4),b])

[ 1  6  7 11]


In [44]:
# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10
print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [ ]:
'''Boolean array indexing: Boolean array indexing lets you pick out arbitrary elements of an array.
Frequently this type of indexing is used to select the elements of an array that satisfy some condition.'''

In [48]:
a = np.array([[1,2], [3, 4], [5, 6]])
bool_idx = (a > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.
            
print(bool_idx)
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])
print(a[a>2])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


In [54]:
x=np.array([1,2])
print(x.dtype)
x=np.array([1,2.32])
print(x.dtype)
x=np.array([1,20],dtype=np.int64)
print(x.dtype)

int32
float64
int64


In [59]:
x=np.array([[1,2],[3,4]],dtype=np.float64)
y=np.array([[5,6],[7,8]],dtype=np.float64)
print(x+y)
print(np.add(x,y))

[[  6.   8.]
 [ 10.  12.]]
[[  6.   8.]
 [ 10.  12.]]


In [61]:
print(x-y)
print(np.subtract(x,y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [63]:
print(x*y)
print(np.multiply(x,y))
print(x / y)
print(np.divide(x, y))
print(np.sqrt(x))

[[  5.  12.]
 [ 21.  32.]]
[[  5.  12.]
 [ 21.  32.]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 1.          1.41421356]
 [ 1.73205081  2.        ]]


In [64]:
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

print(v.dot(w))
print(np.dot(v, w))

219
219


In [65]:
print(x.dot(v))
print(np.dot(x, v))

[29 67]
[29 67]


In [66]:
print(x.dot(y))
print(np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [70]:
import numpy as np

x = np.array([[1,2],[3,4]])
print(x)
print(np.sum(x))  # Compute sum of all elements; prints "10"

[[1 2]
 [3 4]]
10


In [69]:
print(np.sum(x,axis=0)) # Compute sum of each column; prints "[4 6]"

[4 6]


In [71]:
print(np.sum(x,axis=1)) # Compute sum of each row; prints "[3 7]"

[3 7]


In [72]:
import numpy as np

x = np.array([[1,2], [3,4]])

In [73]:
print(x)

[[1 2]
 [3 4]]


In [74]:
print(x.T)

[[1 3]
 [2 4]]


In [75]:
v = np.array([1,2,3])
print(v)    # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"

[1 2 3]
[1 2 3]


In [ ]:
'''Broadcasting
Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes 
when performing arithmetic operations. Frequently we have a smaller array and a larger array, 
and we want to use the smaller array multiple times to perform some operation on the larger array.'''

In [76]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])

In [78]:
y=np.empty_like(x) # Create an empty matrix with the same shape as x
print(y)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [79]:
# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v
    
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [82]:
import numpy as np
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1)) # Stack 4 copies of v on top of each other
print(vv)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [83]:
y = x + vv
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [84]:
vv = np.tile(v, (2, 2)) # Stack 4 copies of v on top of each other
print(vv)

[[1 0 1 1 0 1]
 [1 0 1 1 0 1]]


In [85]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [86]:
import numpy as np

# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)

In [89]:
print(np.reshape(v, (3, 1))*w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [90]:
x = np.array([[1,2,3], [4,5,6]])
print(x + v)

[[2 4 6]
 [5 7 9]]


In [93]:
print((x.T + w).T)
# Another solution is to reshape w to be a column vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.

[[ 5  6  7]
 [ 9 10 11]]


In [94]:
print(x + np.reshape(w, (2, 1)))

[[ 5  6  7]
 [ 9 10 11]]


In [95]:
print(x * 2)

[[ 2  4  6]
 [ 8 10 12]]
